name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Master CI
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: ['latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 7

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      # build first because this produces .d.ts files that `tsc` will need when
      #  linting types in the `lint` step
      - name: Build
        run: pnpm run ci:build

      - name: Lint
        run: pnpm run ci:lint

      - name: Test
        run: pnpm run ci:test
